name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Connect to AWS and Manage main.py on Raspberry Pi
        run: |
          echo "Connecting to AWS instance..."
          ssh -i ~/.ssh/aws_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-13-61-21-51.eu-north-1.compute.amazonaws.com <<EOF
            echo "Connecting to Raspberry Pi via SSH tunnel..."
            sshpass -p "project" ssh -p 2222 -o StrictHostKeyChecking=no facex@localhost <<EOS
              # Check and stop main.py if running
              PID=$(pgrep -f main.py)
              if [ -z "$PID" ]; then
                  echo "main.py is not running."
              else
                  echo "Stopping main.py (PID: $PID)..."
                  kill $PID
                  if [ $? -eq 0 ]; then
                      echo "main.py stopped successfully."
                  else
                      echo "Failed to stop main.py."
                      exit 1
                  fi
              fi

              # Navigate to project directory
              if ! cd /home/facex/facexProject/FaceX-FaceRecognition; then
                  echo "Failed to access project directory."
                  exit 1
              fi

              # Activate virtual environment
              if ! source ../env/bin/activate; then
                  echo "Failed to activate virtual environment."
                  exit 1
              fi

              # Update repository
              if ! git pull; then
                  echo "Failed to update repository."
                  exit 1
              fi

              # Restart main.py in background
              echo "Restarting main.py in the background..."
              nohup python main.py > output.log 2>&1 &
              if [ $? -eq 0 ]; then
                  echo "main.py restarted successfully."
              else
                  echo "Failed to restart main.py."
                  exit 1
              fi
EOS
EOF