name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Déclenchement lors d'un push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/aws_key.pem
        chmod 600 ~/.ssh/aws_key.pem

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Connect to AWS and Manage main.py on Raspberry Pi
      run: |
        echo "Connexion à l'instance AWS"
        ssh -t -i ~/.ssh/aws_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-13-61-21-51.eu-north-1.compute.amazonaws.com << 'EOF'
          echo "Connexion au Raspberry Pi via le tunnel SSH"
          sshpass -p "project" ssh -t -p 2222 -o StrictHostKeyChecking=no facex@localhost "
          # Vérifier et arrêter main.py s'il est en cours d'exécution
          PID=\$(pgrep -f main.py)
          if [ -n \"\$PID\" ]; then
            echo 'Arrêt de main.py (PID: \$PID)...'
            kill \$PID
          else
            echo 'main.py n'est pas en cours d'exécution.'
          fi

          # Aller dans le répertoire du projet
          cd facexProject/FaceX-FaceRecognition/

          # Activer l'environnement virtuel
          source ../env/bin/activate

          # Mettre à jour le dépôt
          git pull

          # Relancer main.py en arrière-plan
          echo 'Relancer main.py en arrière-plan...'
          nohup python main.py > output.log 2>&1 &
          echo 'main.py est relancé.'
          "
        EOF
