name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Déclenchement lors d'un push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/aws_key.pem
        chmod 600 ~/.ssh/aws_key.pem

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Connect to AWS and Run Python Script on Raspberry Pi
      run: |
        echo "Connexion à l'instance AWS"
        ssh -i ~/.ssh/aws_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-13-61-21-51.eu-north-1.compute.amazonaws.com << 'EOF'
          echo "Connexion au Raspberry Pi via le tunnel SSH"
          sshpass -p "project" ssh -p 2222 -o StrictHostKeyChecking=no facex@localhost "cd facexProject/FaceX-FaceRecognition/ && source ../env/bin/activate && python main.py"
        EOF
